window.WORDBANK = [
  ["APE", "Primate"],
  ["ACE", "Top card"],
  ["ACT", "Perform on stage"],
  ["ADD", "Sum up"],
  ["AGE", "Years lived"],
  ["AGO", "In the past"],
  ["AID", "Help"],
  ["AIM", "Target"],
  ["AIR", "What we breathe"],
  ["ANT", "Picnic pest"],
  ["ARM", "Limb with an elbow"],
  ["ART", "Museum display"],
  ["ASK", "Pose a question"],
  ["AXE", "Lumberjack's tool"],
  ["BAG", "Sack"],
  ["BAT", "Baseball club"],
  ["BED", "Place to sleep"],
  ["BEE", "Honey maker"],
  ["BIG", "Large"],
  ["BOX", "Carton"],
  ["BOY", "Young lad"],
  ["BUS", "School transport"],
  ["CAB", "Taxi"],
  ["CAN", "Tin container"],
  ["CAP", "Baseball hat"],
  ["CAR", "Automobile"],
  ["CAT", "Feline pet"],
  ["COW", "Dairy animal"],
  ["CRY", "Weep"],
  ["CUP", "Mug"],
  ["CUT", "Slice"],
  ["DAY", "Twenty-four hours"],
  ["DEN", "Lion's lair"],
  ["DIG", "Use a shovel"],
  ["DOG", "Canine pet"],
  ["DRY", "Not wet"],
  ["DUE", "Owed"],
  ["EAR", "Listening organ"],
  ["EAT", "Have a meal"],
  ["EGG", "Breakfast item from a hen"],
  ["ELF", "Santa's helper"],
  ["END", "Finish"],
  ["EYE", "Organ of sight"],
  ["FAN", "Cooling device"],
  ["FAR", "Distant"],
  ["FIG", "Fruit tree"],
  ["FIX", "Repair"],
  ["FLY", "Buzzing insect"],
  ["FOX", "Sly animal"],
  ["FUN", "Enjoyment"],
  ["FUR", "Animal coat"],
  ["GAS", "Fuel for a car"],
  ["GEM", "Precious stone"],
  ["GYM", "Workout place"],
  ["HAT", "Head covering"],
  ["HEN", "Female chicken"],
  ["HOT", "Very warm"],
  ["HUG", "Warm embrace"],
  ["ICE", "Frozen water"],
  ["INK", "Pen fluid"],
  ["JAM", "Fruit spread"],
  ["JAR", "Glass container"],
  ["JAW", "Chewing bone"],
  ["JET", "Fast plane"],
  ["JOB", "Employment"],
  ["JOG", "Run slowly"],
  ["JOY", "Delight"],
  ["KEY", "Lock opener"],
  ["KID", "Child"],
  ["KIT", "Set of tools"],
  ["LAB", "Science room"],
  ["LAW", "Rule of the land"],
  ["LEG", "Limb with a knee"],
  ["LID", "Pot cover"],
  ["LOG", "Piece of firewood"],
  ["MAP", "Atlas page"],
  ["MIX", "Blend"],
  ["MUD", "Wet dirt"],
  ["NAP", "Short sleep"],
  ["NET", "Fishing mesh"],
  ["NEW", "Not old"],
  ["NUT", "Acorn, e.g."],
  ["OAK", "Mighty tree"],
  ["OIL", "Crude resource"],
  ["OWL", "Night bird"],
  ["OWN", "Possess"],
  ["PAN", "Frying vessel"],
  ["PEN", "Writing tool"],
  ["PET", "Dog or cat at home"],
  ["PIE", "Baked dessert"],
  ["PIG", "Farm oinker"],
  ["POT", "Cooking vessel"],
  ["RAT", "Rodent"],
  ["RAW", "Uncooked"],
  ["RED", "Color of a stop sign"],
  ["RUG", "Floor covering"],
  ["SAW", "Cutting tool"],
  ["SEA", "Ocean"],
  ["SKY", "Blue expanse above"],
  ["SUN", "Star at our center"],
  ["TAX", "April payment"],
  ["TEA", "Brewed drink"],
  ["TEN", "Number of fingers"],
  ["TOE", "Foot digit"],
  ["TOY", "Plaything"],
  ["TWO", "Pair"],
  ["VAN", "Delivery vehicle"],
  ["VET", "Animal doctor"],
  ["WAX", "Candle material"],
  ["WEB", "Spider's creation"],
  ["WET", "Soaked"],
  ["WIG", "Hairpiece"],
  ["WIN", "Victory"],
  ["YAK", "Shaggy ox"],
  ["YAM", "Sweet potato"],
  ["YES", "Affirmative"],
  ["YET", "So far"],
  ["ZAP", "Hit with a ray"],
  ["ZEN", "Calm state of mind"],
  ["ZIP", "Fasten a jacket"],
  ["ZOO", "Animal park"],
  ["EVE", "Night before"],
  ["IVY", "Climbing plant"],
  ["SIX", "Number after five"],
  ["WAY", "Path"],
  ["KEG", "Beer barrel"],
  ["SKI", "Slope glider"],
  ["ELK", "Large deer"],
  ["INN", "Roadside lodge"],
  ["ICY", "Frozen over"],
  ["OAR", "Rowing tool"],
  ["OPT", "Choose"],
  ["ORE", "Mined mineral"],
  ["URN", "Vase for ashes"],
  ["USE", "Employ"],
  ["VOW", "Solemn promise"],
  ["HEX", "Curse"],
  ["FEW", "Not many"],
  ["FOG", "Misty weather"],
  ["FIT", "In good shape"],
  ["TUB", "Place for a bath"],
  ["HAY", "Horse feed"],
  ["DEW", "Morning moisture"],
  ["EMU", "Flightless bird"],
  ["GUM", "Chewy treat"],
  ["HOP", "Jump on one foot"],
  ["HUT", "Small shack"],
  ["RIB", "Chest bone"],
  ["ROW", "Line of seats"],
  ["SPY", "Secret agent"],
  ["TIP", "Gratuity"],
  ["WOK", "Stir-fry pan"],
  ["AWE", "Wonder"],
  ["ZIG", "Sharp turn"],
  ["FEZ", "Tasseled hat"],
  ["ABLE", "Competent"],
  ["ACID", "Lemon juice, e.g."],
  ["AREA", "Region"],
  ["ARMY", "Military force"],
  ["AUNT", "Parent's sister"],
  ["AWAY", "Not home"],
  ["AXIS", "Line of rotation"],
  ["BABY", "Infant"],
  ["BAKE", "Cook in an oven"],
  ["BAND", "Musical group"],
  ["BANK", "Money keeper"],
  ["BARN", "Farm building"],
  ["BEAR", "Grizzly"],
  ["BIKE", "Two-wheeler"],
  ["BIRD", "Feathered flier"],
  ["BLUE", "Color of the sky"],
  ["BOAT", "Watercraft"],
  ["BONE", "Skeleton part"],
  ["BOOK", "Library item"],
  ["CAKE", "Birthday dessert"],
  ["CALM", "Peaceful"],
  ["CAMP", "Tent site"],
  ["CARD", "Greeting mailer"],
  ["CAVE", "Bat's home"],
  ["CITY", "Urban area"],
  ["CLAY", "Potter's material"],
  ["COAT", "Winter wear"],
  ["CODE", "Secret cipher"],
  ["COIN", "Penny, e.g."],
  ["COLD", "Chilly"],
  ["COOK", "Chef"],
  ["CORN", "Cob vegetable"],
  ["CRAB", "Clawed crustacean"],
  ["DARK", "Unlit"],
  ["DATE", "Calendar day"],
  ["DEER", "Forest animal with antlers"],
  ["DESK", "Office table"],
  ["DICE", "Game cubes"],
  ["DIVE", "Plunge into water"],
  ["DOVE", "Bird of peace"],
  ["DOOR", "Entry"],
  ["DUCK", "Quacker"],
  ["DUST", "Household dirt"],
  ["EASY", "Simple"],
  ["ECHO", "Repeated sound"],
  ["EDGE", "Border"],
  ["EPIC", "Grand story"],
  ["EVEN", "Level"],
  ["EXAM", "Test"],
  ["EXIT", "Way out"],
  ["FACE", "Front of the head"],
  ["FARM", "Rural spread"],
  ["FAST", "Quick"],
  ["FISH", "Aquarium swimmer"],
  ["FIVE", "Fingers on one hand"],
  ["FLAG", "National banner"],
  ["FOOD", "Nourishment"],
  ["FORK", "Dinner utensil with tines"],
  ["FROG", "Pond hopper"],
  ["FUZZ", "Peach coating"],
  ["GAME", "Match"],
  ["GIFT", "Present"],
  ["GOAT", "Bearded farm animal"],
  ["GOLD", "Precious metal"],
  ["GOLF", "Game with tees"],
  ["GRAY", "Ash color"],
  ["HAND", "Palm holder"],
  ["HAWK", "Bird of prey"],
  ["HALF", "One of two equal parts"],
  ["HERO", "Brave figure"],
  ["HIKE", "Trail walk"],
  ["HOME", "Place of residence"],
  ["HOOK", "Fishing line gear"],
  ["IDEA", "Bright thought"],
  ["INCH", "Twelfth of a foot"],
  ["IRON", "Pressing appliance"],
  ["ITEM", "Thing on a list"],
  ["JAZZ", "Music with improvisation"],
  ["JEEP", "Off-road vehicle"],
  ["JOKE", "Gag"],
  ["JUMP", "Leap"],
  ["JURY", "Trial panel"],
  ["JUST", "Fair"],
  ["KEEN", "Eager"],
  ["KICK", "Punt"],
  ["KING", "Royal ruler"],
  ["KITE", "Windy-day flier"],
  ["KNEE", "Leg joint"],
  ["KNOT", "Tied loop"],
  ["LAKE", "Body of fresh water"],
  ["LAMB", "Young sheep"],
  ["LAMP", "Desk light"],
  ["LAZY", "Idle"],
  ["LEAF", "Tree foliage piece"],
  ["LION", "King of the jungle"],
  ["LOVE", "Deep affection"],
  ["LUCK", "Fortune"],
  ["MASK", "Face cover"],
  ["MAZE", "Labyrinth"],
  ["MILK", "Dairy drink"],
  ["MOON", "Night light in the sky"],
  ["MYTH", "Legend"],
  ["NAVY", "Sea force"],
  ["NEST", "Bird's home"],
  ["NEXT", "Following"],
  ["NOSE", "Smelling organ"],
  ["OBEY", "Follow orders"],
  ["OKAY", "All right"],
  ["OVEN", "Baking box"],
  ["OVER", "Finished"],
  ["PARK", "Green space"],
  ["PINK", "Light red"],
  ["POEM", "Verse"],
  ["QUIZ", "Short test"],
  ["QUIT", "Stop"],
  ["QUAD", "College lawn"],
  ["RAIN", "Precipitation"],
  ["ROCK", "Stone"],
  ["ROPE", "Thick cord"],
  ["ROSE", "Thorny flower"],
  ["RUBY", "Red gem"],
  ["SAFE", "Secure"],
  ["SALT", "Table seasoning"],
  ["SHIP", "Ocean vessel"],
  ["SHOE", "Footwear"],
  ["SNOW", "Winter flakes"],
  ["SOAP", "Bathing bar"],
  ["SOUP", "Bowl of broth"],
  ["STAR", "Twinkler in the night"],
  ["SWIM", "Do laps"],
  ["TAXI", "Yellow cab"],
  ["TOWN", "Village"],
  ["TREE", "Oak or elm"],
  ["TUNA", "Canned fish"],
  ["UGLY", "Unattractive"],
  ["UNIT", "Single measure"],
  ["VASE", "Flower holder"],
  ["VERB", "Action word"],
  ["VIEW", "Scenic sight"],
  ["VOTE", "Cast a ballot"],
  ["WAVE", "Ocean swell"],
  ["WHIP", "Beat cream"],
  ["WOLF", "Pack animal"],
  ["WORK", "Labor"],
  ["YARD", "Lawn area"],
  ["YAWN", "Sleepy mouth sign"],
  ["YEAR", "Twelve months"],
  ["YOGA", "Stretching practice"],
  ["YOLK", "Egg center"],
  ["ZERO", "Nothing"],
  ["ZONE", "Area"],
  ["ZOOM", "Speed by"],
  ["OXEN", "Plow pullers"],
  ["FLEX", "Show muscles"],
  ["APEX", "Peak"],
  ["JAVA", "Coffee"],
  ["MINK", "Fur animal"],
  ["HAZE", "Mist"],
  ["AQUA", "Blue-green"],
  ["ENVY", "Jealousy"],
  ["KIWI", "Fuzzy fruit"],
  ["WINK", "Flirtatious eye signal"],
  ["SOFA", "Couch"],
  ["FAWN", "Baby deer"],
  ["ABOUT", "Concerning"],
  ["ACORN", "Oak seed"],
  ["ADULT", "Grown-up"],
  ["AGREE", "Concur"],
  ["ALARM", "Wake-up signal"],
  ["ALIVE", "Living"],
  ["APPLE", "Orchard fruit"],
  ["ARROW", "Archer's shot"],
  ["AWAKE", "Not sleeping"],
  ["BACON", "Breakfast strips"],
  ["BEACH", "Sandy shore"],
  ["BLACK", "Darkest color"],
  ["BRAIN", "Thinking organ"],
  ["BREAD", "Loaf"],
  ["BRICK", "Building block"],
  ["CANDY", "Sweets"],
  ["CHAIR", "Seat"],
  ["CHESS", "Game with kings and pawns"],
  ["CLOCK", "Timekeeper"],
  ["CLOUD", "Sky puff"],
  ["CRANE", "Tall wading bird"],
  ["CROWN", "Royal headwear"],
  ["DANCE", "Waltz, e.g."],
  ["DOZEN", "Twelve"],
  ["DREAM", "Night vision"],
  ["DRINK", "Beverage"],
  ["EAGLE", "National bird"],
  ["EARTH", "Our planet"],
  ["EIGHT", "Number of spider legs"],
  ["ENJOY", "Relish"],
  ["EQUAL", "Even-steven"],
  ["EQUIP", "Outfit with gear"],
  ["EXTRA", "Additional"],
  ["FABLE", "Aesop story"],
  ["FAIRY", "Tooth collector"],
  ["FEAST", "Big meal"],
  ["FIELD", "Meadow"],
  ["FLAME", "Fire's glow"],
  ["FLOOR", "Ground level"],
  ["FRUIT", "Apple or pear"],
  ["GHOST", "Specter"],
  ["GIANT", "Huge"],
  ["GLASS", "Window material"],
  ["GRAPE", "Vine fruit"],
  ["GRASS", "Lawn cover"],
  ["HAPPY", "Joyful"],
  ["HEART", "Blood pumper"],
  ["HONEY", "Bee product"],
  ["HORSE", "Stable animal"],
  ["HOUSE", "Home"],
  ["IGLOO", "Ice house"],
  ["IVORY", "Tusk material"],
  ["JELLY", "Toast spread"],
  ["JEWEL", "Gem"],
  ["JOINT", "Knee or elbow"],
  ["JUDGE", "Court official"],
  ["JUICE", "Orange drink"],
  ["JUMBO", "Extra large"],
  ["KAYAK", "Paddled boat"],
  ["KNIFE", "Sharp utensil"],
  ["KOALA", "Eucalyptus eater"],
  ["LEMON", "Sour fruit"],
  ["LIGHT", "Not heavy"],
  ["LUNCH", "Midday meal"],
  ["MAGIC", "Wizard's art"],
  ["MAJOR", "Army rank"],
  ["MANGO", "Tropical fruit"],
  ["MAPLE", "Syrup tree"],
  ["MONEY", "Cash"],
  ["MOUSE", "Computer pointer"],
  ["MUSIC", "Songs and tunes"],
  ["NIGHT", "Dark hours"],
  ["NOVEL", "Long fiction book"],
  ["OCEAN", "Atlantic, e.g."],
  ["OLIVE", "Martini garnish"],
  ["ONION", "Tear-inducing veggie"],
  ["ORBIT", "Planet's path"],
  ["OTTER", "Playful river swimmer"],
  ["OZONE", "Layer in the upper atmosphere"],
  ["PAINT", "Artist's medium"],
  ["PANDA", "Bamboo eater"],
  ["PIANO", "Keyboard instrument"],
  ["PIZZA", "Pie with toppings"],
  ["PLANT", "Grow seeds"],
  ["POKER", "Card game with bluffing"],
  ["QUACK", "Duck's sound"],
  ["QUEEN", "Royal woman"],
  ["QUEST", "Epic journey"],
  ["QUICK", "Fast"],
  ["QUIET", "Silent"],
  ["QUILT", "Patchwork cover"],
  ["RADIO", "FM device"],
  ["RAVEN", "Black bird"],
  ["RIVER", "Nile, e.g."],
  ["ROBOT", "Machine helper"],
  ["SHEEP", "Wool source"],
  ["SMILE", "Happy face"],
  ["SNAKE", "Slithering reptile"],
  ["SPOON", "Soup utensil"],
  ["STORM", "Tempest"],
  ["SUGAR", "Sweetener"],
  ["TABLE", "Dining furniture"],
  ["TIGER", "Striped cat"],
  ["TOAST", "Browned bread"],
  ["TOWEL", "Bath drier"],
  ["TRAIN", "Railway vehicle"],
  ["UNCLE", "Parent's brother"],
  ["UNITY", "Oneness"],
  ["VALVE", "Flow control"],
  ["VIDEO", "Recorded footage"],
  ["VIVID", "Bright and intense"],
  ["VOICE", "Singing sound"],
  ["WAGON", "Covered cart"],
  ["WATER", "H2O"],
  ["WHALE", "Ocean giant"],
  ["WORLD", "Globe"],
  ["YACHT", "Luxury boat"],
  ["YOUTH", "Early life"],
  ["YOUNG", "Youthful"],
  ["ZEBRA", "Striped animal"],
  ["BLAZE", "Big fire"],
  ["CRAZY", "Wild"],
  ["FROZE", "Turned to ice"],
  ["PRIZE", "Award"],
  ["WALTZ", "Ballroom dance"],
  ["FIZZY", "Bubbly"],
  ["TOXIC", "Poisonous"],
  ["BOXER", "Ring fighter"],
  ["EXACT", "Precise"],
  ["RELAX", "Unwind"],
  ["PIXEL", "Screen dot"],
  ["SIXTY", "Number after fifty-nine"],
  ["JOKER", "Wild card"],
  ["BANJO", "Plucked instrument"],
  ["JUMPY", "Nervous"],
  ["KNOCK", "Rap on a door"],
  ["SKUNK", "Smelly critter"],
  ["AWFUL", "Terrible"],
  ["FLUTE", "Wind instrument"],
  ["FUDGE", "Chocolate treat"],
  ["SQUID", "Inky sea creature"],
  ["SQUAD", "Team"],
  ["QUOTA", "Set amount"],
  ["QUOTE", "Cite"],
  ["SWORD", "Knight's blade"],
  ["WHEAT", "Bread grain"],
  ["OWNER", "Possessor"],
  ["BROWN", "Chocolate color"],
  ["TOWER", "Tall structure"],
  ["LEVEL", "Flat"],
  ["SEVEN", "Days in a week"],
  ["GLOVE", "Hand warmer"],
  ["MOVIE", "Film"],
  ["ROYAL", "Kingly"],
  ["YIELD", "Give way"],
  ["ENEMY", "Foe"],
  ["EMPTY", "Hollow"],
  ["DAISY", "Flower"],
  ["PARTY", "Celebration"],
  ["STYLE", "Fashion"],
];
